"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](blue)\
$os\
[ ](bg:red fg:blue)\
$username\
[ ](red)\
$directory\
$git_branch\
$git_status\
$fill\
$line_break\
$character
"""

[os]
disabled = false
style = "bg:blue fg:white"

[username]
disabled = false
show_always = true
style_user = "bg:red"
format = '[$user ]($style)'
